### PR TITLE
iconSize Slider + updated UNNECESSARY ELEMENTS

### PR DESCRIPTION
**Pull request by black-backdoor**
Add a Slider in the Settings Menu for the Size of the Icons as described in this issue #5

### CODE REVIEW

**Comment by Hutch79** [comment]
I'm currently editing the pr as well as adding a new idea I had.

**Review by black-backdoor — COMMENTED** [review]
please change iconSize back to how it was before

Values in Slider
[default, min, max, step, units]

**Comment by Hutch79** [comment]
> default shoud be 20 since this was how it was before the range was added  

Good point.
But I'll leave the max at 50 which disables the size changes completely.

**Comment by black-backdoor** [comment]
> @black-backdoor I changed the default size to 30 which was the default value from before the "change size" option.

image

**Comment by Hutch79** [comment]
I'm talking about the `.activityiconcontainer` which is the one changing the layout size.  
`.activityicon` can't be larger than `.activityiconcontainer` so it's unnecessary for the layout size.

Also, the Screenshot you provided is an old version which is your original commit.  
This was changed by me with the following:
image


The Slider directly represents the size of `.activityiconcontainer` since It's critical in adjusting the page Layout, not the icon.
Therefore, the default values are exactly the same as before this PR.

**Comment by Pianonic** [comment]
lol

**Review by Hutch79 — DISMISSED** [review]
Looks good

**Comment by black-backdoor** [comment]
> @black-backdoor I changed the default size to 30 which was the default value from before the "change size" option.

for me its just important that, without me having to go change the settings, the icon size is the same as before we added the slider

so the original sizes for `.activityiconcontainer` were 30px and for  `.activityicon` it was 20px

**Comment by black-backdoor** [comment]
the `smallerIcons` dosn't do anything

**Review by Hutch79 — CHANGES_REQUESTED** [review]
The Hide Link List feature sometimes removes the wrong block (Boost Theme).
Course ID 654 for example.

Please also check features with the Boost Theme, not only with the Classic. Especially because Boost is the default theme!

**Comment by black-backdoor** [comment]
fixed with last commit

**Review by Hutch79 — APPROVED** [review]

**Pull request merged**
